/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

/**
 *
 * @author win8
 */
import project_pl1.Car;
import project_pl1.Brand;
public class Add_CarPanel extends javax.swing.JPanel {

    /**
     * Creates new form Add_CarPanel
     */
    public Add_CarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldcarnumber = new javax.swing.JTextField();
        jComboBoxtype = new javax.swing.JComboBox<>();
        jTextFieldenginecapacity = new javax.swing.JTextField();
        jTextFieldcapacity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldcompanybrand = new javax.swing.JTextField();
        jTextFieldmakeyear = new javax.swing.JTextField();
        jComboBoxvariant = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        labelSucess = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldrentvalue = new javax.swing.JTextField();
        jComboBoxUseAs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sitting Capacity");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Car Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Engine Capcity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Type");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Variant");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Make Year");

        jComboBoxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Not AC" }));
        jComboBoxtype.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxtypeComponentShown(evt);
            }
        });
        jComboBoxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtypeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Company Brand");

        jTextFieldmakeyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmakeyearActionPerformed(evt);
            }
        });

        jComboBoxvariant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base Model", "Economic Model", "Top Model" }));
        jComboBoxvariant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxvariantActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 88, 109));
        jButton1.setText("Add Car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rent Value");

        jComboBoxUseAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taxi", "Individual" }));

        jLabel3.setText("Use As");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldenginecapacity)
                            .addComponent(jTextFieldcarnumber)
                            .addComponent(jTextFieldcompanybrand)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldmakeyear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldcapacity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxvariant, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldrentvalue)
                            .addComponent(jComboBoxUseAs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelSucess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldcompanybrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldcarnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldrentvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldenginecapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxvariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUseAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldmakeyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxtypeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxtypeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtypeComponentShown

    private void jComboBoxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtypeActionPerformed

    private void jTextFieldmakeyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmakeyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmakeyearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!jTextFieldcarnumber.getText().equals("")&&!jTextFieldcapacity.getText().equals("")&&!jTextFieldenginecapacity.getText().equals("")&&!jTextFieldcompanybrand.getText().equals("")&&!jTextFieldmakeyear.getText().equals("")&&!jTextFieldrentvalue.getText().equals("")){
            Car x=new Car();
            x.setCarNo(Integer.parseInt(jTextFieldcarnumber.getText()));
            x.setcapacity(Integer.parseInt(jTextFieldcapacity.getText()));
            x.setEngineCapacity(jTextFieldenginecapacity.getText());
            x.setMakeYear(jTextFieldmakeyear.getText());
            x.Brands.setBName(jTextFieldcompanybrand.getText());
            x.setStatus("Not Rented");
            x.setRent_Value(Integer.parseInt(jTextFieldrentvalue.getText()));

            if(jComboBoxtype.getSelectedItem().equals("AC")){
                x.setType("AC");
            }
            else if(jComboBoxtype.getSelectedItem().equals("Not AC")){
                x.setType("Not AC");
            }
            if(jComboBoxvariant.getSelectedItem().equals("Base Model")){
                x.setvariant("Base Model");
            }
            else if(jComboBoxvariant.getSelectedItem().equals("Economic Model")){
                x.setvariant("Economic Model");
            }
            else if(jComboBoxvariant.getSelectedItem().equals("Top Model")){
                x.setvariant("Top Model");
            }
            if(jComboBoxUseAs.getSelectedItem().equals("Taxi")){
                x.setUseAs("Taxi");
            }else if(jComboBoxUseAs.getSelectedItem().equals("Individual")){
                x.setUseAs("Individual");
            }
            if(x.Add_Car()){
                labelSucess.setText("Added Sucessfully.....");
                resetPanelData();
            }
            else{
                labelSucess.setText("Failed to add.....!");
            }
        }else{
            labelSucess.setText("Missing Requird Fields..!Please Complete the Data");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxvariantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxvariantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxvariantActionPerformed
    protected void resetPanelData(){
        jTextFieldcompanybrand.setText("");
        jTextFieldcapacity.setText("");
        jTextFieldenginecapacity.setText("");
        jTextFieldmakeyear.setText("");
        jTextFieldcarnumber.setText("");
        
        jComboBoxtype.setSelectedIndex(0);
        jComboBoxvariant.setSelectedIndex(0);
//        BrandIDTextField.setText("");
        jTextFieldrentvalue.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxUseAs;
    private javax.swing.JComboBox<String> jComboBoxtype;
    private javax.swing.JComboBox<String> jComboBoxvariant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextFieldcapacity;
    private javax.swing.JTextField jTextFieldcarnumber;
    private javax.swing.JTextField jTextFieldcompanybrand;
    private javax.swing.JTextField jTextFieldenginecapacity;
    private javax.swing.JTextField jTextFieldmakeyear;
    private javax.swing.JTextField jTextFieldrentvalue;
    private javax.swing.JLabel labelSucess;
    // End of variables declaration//GEN-END:variables
}
