/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import project_pl1.Car;

/**
 *
 * @author ali
 */
public class CarViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarViewJPanel
     */
    public CarViewJPanel() {
        initComponents();
        AddRowstoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CarsTable = new javax.swing.JTable();

        CarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand Name", "Car No", "Usa As", "Type", "Variant"
            }
        ));
        jScrollPane1.setViewportView(CarsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

 public void AddRowstoTable(){  
      DefaultTableModel model = (DefaultTableModel) CarsTable.getModel();
    int cont =  model.getRowCount();

   
     Object []Row = new Object[5];
     Car c = new Car();
//     Brand b = new Brand();
     ArrayList<Car> Cars = new ArrayList<Car>();
//     ArrayList<Car> v = new ArrayList<Car>();
     Cars = c.ListAllCars();
     for(Car x : Cars){
     
        Row[0]=x.Brands.getBName();
        Row[1]=x.getCarNo();
         Row[2]=x.getUseAs();
         Row[3]=x.getType();
         Row[4]=x.getvariant();

         model.addRow(Row);
     
         
         
        }
       
     
     
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
