/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import project_pl1.Driver;
/**
 *
 * @author Ahmed
 */
public class Driver_ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form Driver_ListPanel
     */
    public Driver_ListPanel() {
        initComponents();
         AddRowsTotable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DriverTable = new javax.swing.JTable();

        DriverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "Address", "Experience", "phone Number", "Date Of Birth", "Gender", "photot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DriverTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public void AddRowsTotable(){
        DefaultTableModel model = (DefaultTableModel) DriverTable.getModel();
        Object []Row = new Object[8];
        
        Driver div = new Driver();
        
        ArrayList<Driver> Drivers = new ArrayList<>();
        Drivers = div.ListAllDriver();
        for (Driver e : Drivers){
            Row[0] = e.getId();
            Row[1] = e.getName();
            Row[2] = e.getAddress();
            Row[3] = e.getExperience();
            Row[4] = e.getPhone_No();
            Row[5] = e.getDate_Of_Birth();
            Row[6] = e.getGender();
            Row[7] = e.getPhoto();
            
            
            model.addRow(Row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DriverTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
