/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import project_pl1.Employee;

/**
 *
 * @author ali
 */
public class List_panel_Employee extends javax.swing.JPanel {

    /**
     * Creates new form List_panel_Employee
     */
    public List_panel_Employee() {
        initComponents();
        AddRowsTotable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();

        EmployeeTable.setBackground(new java.awt.Color(255, 255, 255));
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password", "Name", "ID", "Phone No", "Date of join", "Gender", "Date of birth", "Qualification", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void AddRowsTotable(){
        DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
        Object []Row = new Object[10];
        
        Employee emp = new Employee();
        
        ArrayList<Employee>Employees = new ArrayList<>();
        Employees = emp.ListEmployees();
        if(Employees!=null)
        for (Employee e : Employees){
            Row[0] = e.getUsername();
            Row[1] = e.getPassword();
            Row[2] = e.getName();
            Row[3] = e.getId();
            Row[4] = e.getPhone_No();
            Row[5] = e.Get_Date_of_join();
            Row[6] = e.getGender();
            Row[7] = e.getDate_Of_Birth();
            Row[8] = e.Get_qualification();
            Row[9] = e.getAddress();
            model.addRow(Row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
