/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import com.sun.jndi.toolkit.dir.SearchFilter;
import project_pl1.Employee;

/**
 *
 * @author ali
 */
public class Update_Employee_panel extends javax.swing.JPanel {

    /**
     * Creates new form Update_Employee_panel
     */
    public Update_Employee_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserNameTextField1 = new javax.swing.JTextField();
        PasswordTextField1 = new javax.swing.JTextField();
        IDTextField1 = new javax.swing.JTextField();
        PhoneNoTextField1 = new javax.swing.JTextField();
        NameTextField1 = new javax.swing.JTextField();
        AddressTextField1 = new javax.swing.JTextField();
        DOJTextField1 = new javax.swing.JTextField();
        GenderComboBox1 = new javax.swing.JComboBox<>();
        DOBTextField1 = new javax.swing.JTextField();
        QualificationComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        SearchButton.setBackground(new java.awt.Color(0, 88, 109));
        SearchButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchTextField.setBackground(new java.awt.Color(255, 255, 255));
        SearchTextField.setForeground(new java.awt.Color(0, 0, 0));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 88, 109));
        UpdateButton.setForeground(new java.awt.Color(0, 0, 0));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(0, 88, 109));
        DeleteButton.setForeground(new java.awt.Color(0, 0, 0));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Phone No");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Gender");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Date of join");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date of birth");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Qualification");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("User Name");

        UserNameTextField1.setBackground(java.awt.Color.white);

        PasswordTextField1.setBackground(java.awt.Color.white);

        IDTextField1.setBackground(java.awt.Color.white);
        IDTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextField1ActionPerformed(evt);
            }
        });

        PhoneNoTextField1.setBackground(java.awt.Color.white);
        PhoneNoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoTextField1ActionPerformed(evt);
            }
        });

        NameTextField1.setBackground(java.awt.Color.white);
        NameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextField1ActionPerformed(evt);
            }
        });

        AddressTextField1.setBackground(java.awt.Color.white);
        AddressTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextField1ActionPerformed(evt);
            }
        });

        DOJTextField1.setBackground(java.awt.Color.white);

        GenderComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        GenderComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        GenderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderComboBox1.setToolTipText("");
        GenderComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboBox1ActionPerformed(evt);
            }
        });

        DOBTextField1.setBackground(new java.awt.Color(255, 255, 255));

        QualificationComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        QualificationComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        QualificationComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fresh graduate", "experience", "student" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DOJTextField1)
                                            .addComponent(PasswordTextField1)
                                            .addComponent(GenderComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DOBTextField1)
                                            .addComponent(QualificationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(NameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PhoneNoTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserNameTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton))
                        .addGap(18, 18, 18)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UserNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PhoneNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(NameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(GenderComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(DOJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(DOBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(QualificationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(UpdateButton))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        if(!IDTextField1.getText().equals("")&&!UserNameTextField1.getText().equals("")&&!NameTextField1.getText().equals("")&&!PasswordTextField1.getText().equals("")&&!PhoneNoTextField1.getText().equals("")&&!AddressTextField1.getText().equals("")&&!DOBTextField1.getText().equals("")&&!DOJTextField1.getText().equals("")){
              Employee  emp = new Employee();
              
                emp.setId(Integer.parseInt(IDTextField1.getText()));
                emp.setAddress(AddressTextField1.getText());
                emp.setName(NameTextField1.getText());
                emp.setUsername(UserNameTextField1.getText());
                emp.setPassword(PasswordTextField1.getText());
                emp.setPhone_No(PhoneNoTextField1.getText());
                emp.Set_Date_of_join(DOJTextField1.getText());
                emp.setDate_Of_Birth(DOBTextField1.getText());
                if(GenderComboBox1.getSelectedItem().equals("Male")){
                    emp.setGender("Male");
                }else if(GenderComboBox1.getSelectedItem().equals("Female")){
                    emp.setGender("Female");
                }
                if(QualificationComboBox1.getSelectedItem().equals("fresh graduate")){
                    emp.Set_qualifications("fresh graduate");
                }else if(QualificationComboBox1.getSelectedItem().equals("experience")){
                       emp.Set_qualifications("experience"); 
                }else if(QualificationComboBox1.getSelectedItem().equals("student")){
                    emp.Set_qualifications("student");
                }
                if(emp.Update_Employee(Integer.parseInt(IDTextField1.getText()), emp)){
                  ErrorLabel.setText("Uppdated Successfully");
                     ResetpanelData();
                }else{
                     ErrorLabel.setText("Failed to Add ...!");
                 }
        }else{
              ErrorLabel.setText(" Please fill the Empty Fields ....");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed
    public void ResetpanelData(){
        QualificationComboBox1.setSelectedIndex(0);
        GenderComboBox1.setSelectedIndex(0);
        
        IDTextField1.setText("");
        NameTextField1.setText("");
        PasswordTextField1.setText("");
        UserNameTextField1.setText("");
        DOBTextField1.setText("");
        DOJTextField1.setText("");
        PhoneNoTextField1.setText("");
        AddressTextField1.setText("");
    }
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if(!SearchTextField.getText().equals("")){
            Employee emp  = new Employee();
            Employee retrived = emp.Search_For_Employee(SearchTextField.getText());
            
            if(retrived.getId()>0){
                ErrorLabel.setText("Found....");
                setPanelData(retrived);
            }else{
                ErrorLabel.setText("Not Found.......!!");
            }
        }else{
            ErrorLabel.setText(" Please fill the Search Field ....");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed
    public void setPanelData(Employee emp){
        IDTextField1.setText(""+emp.getId());
        NameTextField1.setText(""+emp.getName());
        AddressTextField1.setText(""+emp.getAddress());
        UserNameTextField1.setText(""+emp.getUsername());
        PasswordTextField1.setText(""+emp.getPassword());
        PhoneNoTextField1.setText(""+emp.getPhone_No());
        DOBTextField1.setText(""+emp.getDate_Of_Birth());
        DOJTextField1.setText(""+emp.Get_Date_of_join());
        if(emp.getGender().equals("Male")){
            GenderComboBox1.setSelectedIndex(0);
        }else if(emp.getGender().equals("Female")){
            GenderComboBox1.setSelectedIndex(1);
        }
        if(emp.Get_qualification().equals("fresh graduate")){
            QualificationComboBox1.setSelectedItem("fresh graduate");
        }else if(emp.Get_qualification().equals("experience")){
            QualificationComboBox1.setSelectedItem("experience");
            
        }else if(emp.Get_qualification().equals("student")){
             QualificationComboBox1.setSelectedItem("student");
        }
    }
    private void IDTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextField1ActionPerformed

    private void NameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextField1ActionPerformed

    private void PhoneNoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoTextField1ActionPerformed

    private void AddressTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextField1ActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if(!SearchTextField.getText().equals("")){
            Employee emp = new Employee();
            if(emp.Delete_Employee(Integer.parseInt(IDTextField1.getText()))){
                ErrorLabel.setText("Deleted Successfully ");
                ResetpanelData();
            }else{
                ErrorLabel.setText("Failed to Delete ...!!");
            }
        }else{
            ErrorLabel.setText(" Please fill the Empty Fields ....");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void GenderComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboBox1ActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField1;
    private javax.swing.JTextField DOBTextField1;
    private javax.swing.JTextField DOJTextField1;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JComboBox<String> GenderComboBox1;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JTextField NameTextField1;
    private javax.swing.JTextField PasswordTextField1;
    private javax.swing.JTextField PhoneNoTextField1;
    private javax.swing.JComboBox<String> QualificationComboBox1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UserNameTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
