/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.Panels.Add_Employee_panel;
import Frames.Panels.List_panel_Employee;
import Frames.Panels.Update_Employee_panel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
/**
 *
 * @author ali
 */
public class Admin_Employee_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Employee_Frame
     */
    Add_Employee_panel e1;
    List_panel_Employee e2;
    Update_Employee_panel e3;
    GridBagLayout layout = new GridBagLayout();
    public Admin_Employee_Frame() {
        initComponents();
        
        e1 = new Add_Employee_panel();
        e2 = new List_panel_Employee();
        e3 = new Update_Employee_panel();
        
        Dynamic_Panel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        
        Dynamic_Panel.add(e1,c);
        Dynamic_Panel.add(e2,c);
        Dynamic_Panel.add(e3,c);
       
        e1.setVisible(true);
        e1.setVisible(false);
        e2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add_Employee_Button = new javax.swing.JButton();
        List_All_Employees_Button = new javax.swing.JButton();
        Update_Employee_Button = new javax.swing.JButton();
        Dynamic_Panel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Employee ");

        jPanel1.setBackground(new java.awt.Color(0, 88, 109));

        Add_Employee_Button.setBackground(new java.awt.Color(255, 255, 255));
        Add_Employee_Button.setText("Add Employee");
        Add_Employee_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Employee_ButtonActionPerformed(evt);
            }
        });

        List_All_Employees_Button.setBackground(new java.awt.Color(255, 255, 255));
        List_All_Employees_Button.setText("List Employees");
        List_All_Employees_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_All_Employees_ButtonActionPerformed(evt);
            }
        });

        Update_Employee_Button.setBackground(new java.awt.Color(255, 255, 255));
        Update_Employee_Button.setText("Update Employee");
        Update_Employee_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Employee_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Employee_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Update_Employee_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(List_All_Employees_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Add_Employee_Button)
                .addGap(74, 74, 74)
                .addComponent(List_All_Employees_Button)
                .addGap(89, 89, 89)
                .addComponent(Update_Employee_Button)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        Dynamic_Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Dynamic_PanelLayout = new javax.swing.GroupLayout(Dynamic_Panel);
        Dynamic_Panel.setLayout(Dynamic_PanelLayout);
        Dynamic_PanelLayout.setHorizontalGroup(
            Dynamic_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        Dynamic_PanelLayout.setVerticalGroup(
            Dynamic_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        getContentPane().add(Dynamic_Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Employee_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Employee_ButtonActionPerformed
        e1.setVisible(true);
        e2.setVisible(false);
        e3.setVisible(false);
    }//GEN-LAST:event_Add_Employee_ButtonActionPerformed

    private void List_All_Employees_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_All_Employees_ButtonActionPerformed
        e2.setVisible(true);
        e1.setVisible(false);
        e3.setVisible(false);
    }//GEN-LAST:event_List_All_Employees_ButtonActionPerformed

    private void Update_Employee_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Employee_ButtonActionPerformed
        e3.setVisible(true);
        e1.setVisible(false);
        e2.setVisible(false);
    }//GEN-LAST:event_Update_Employee_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Employee_Button;
    private javax.swing.JPanel Dynamic_Panel;
    private javax.swing.JButton List_All_Employees_Button;
    private javax.swing.JButton Update_Employee_Button;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
