/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.Panels.TicketPrint;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Rewas
 */
public class TicketFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TicketFrame
     */
    TicketPrint TP;
    GridBagLayout layout =new GridBagLayout();
    public TicketFrame() {
        
        initComponents();
        TP=new TicketPrint();
        DynamicPanalTicket.setLayout(layout);
        GridBagConstraints c=new  GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanalTicket.add(TP, c);
        TP.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanalTicket = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ticket");

        DynamicPanalTicket.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPanalTicketLayout = new javax.swing.GroupLayout(DynamicPanalTicket);
        DynamicPanalTicket.setLayout(DynamicPanalTicketLayout);
        DynamicPanalTicketLayout.setHorizontalGroup(
            DynamicPanalTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        DynamicPanalTicketLayout.setVerticalGroup(
            DynamicPanalTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanalTicket, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanalTicket;
    // End of variables declaration//GEN-END:variables
}
