/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GGUI.newpackage;
import Frames.Admin_Employee_Frame;
import Frames.Admin_CarFrame;
import Frames.DriverView;
import Frames.Email;
import Frames.Panels.ListDrivers;
import java.util.ArrayList;
import javafx.scene.chart.BarChart;
import org.jfree.ui.RefineryUtilities;
import project_pl1.Car;
import project_pl1.Barchart;

public class AdminDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EmailMenuItem = new javax.swing.JMenuItem();
        StatusReportMenuItem = new javax.swing.JMenuItem();
        UseAsMenuItem = new javax.swing.JMenuItem();
        DriversMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        UserMenu = new javax.swing.JMenu();
        EmployeeMenuItem = new javax.swing.JMenuItem();
        CarMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminDashBoard");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        EmailMenuItem.setText("Email");
        EmailMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(EmailMenuItem);

        StatusReportMenuItem.setText(" Report Status");
        StatusReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusReportMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(StatusReportMenuItem);

        UseAsMenuItem.setText("Report Use As");
        UseAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseAsMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(UseAsMenuItem);

        DriversMenuItem.setText("View Drivers");
        DriversMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriversMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(DriversMenuItem);

        ExitMenuItem.setText("Sign Out");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        UserMenu.setText("Users");
        UserMenu.setAutoscrolls(true);

        EmployeeMenuItem.setText("Employee");
        EmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(EmployeeMenuItem);

        CarMenuItem.setText("Car");
        CarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(CarMenuItem);

        jMenuBar1.add(UserMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
       Login l = new Login();
       l.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void EmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeMenuItemActionPerformed
        Admin_Employee_Frame x = new Admin_Employee_Frame();
        Desktop.add(x);
        x.setVisible(true);
    }//GEN-LAST:event_EmployeeMenuItemActionPerformed

    private void CarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarMenuItemActionPerformed
       Admin_CarFrame x = new Admin_CarFrame();
       Desktop.add(x);
       x.setVisible(true);
    }//GEN-LAST:event_CarMenuItemActionPerformed

    private void EmailMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailMenuItemActionPerformed
      Email e = new Email();
      Desktop.add(e);
      e.setVisible(true);
    }//GEN-LAST:event_EmailMenuItemActionPerformed

    private void StatusReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusReportMenuItemActionPerformed
             Car c=new Car();
        ArrayList<Car> cars= c.ListAllCars();
        String [] Names = new String[cars.size()];
        int [] Status = new int[cars.size()];
        for(int i=0;i<cars.size();i++)
        {
            if (cars.get(i).getStatus().equals("Rented")) {
                Status[i]=2;
            }
            else
            {
                Status [i]=1;
            }
            Names[i]=cars.get(i).getBrands().getBName()+""+cars.get(i).getCarNo();
        }
        String Explain="Car Use\n 1 is Not Rented use\n2 is Rented";
        String Explain_2="Status Of Car";
        Barchart chart = new Barchart("Car Status Report", Names, Status,Explain,Explain_2);

        chart.pack();
        RefineryUtilities.centerFrameOnScreen(chart);
        chart.setVisible(true);
    }//GEN-LAST:event_StatusReportMenuItemActionPerformed

    private void DriversMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriversMenuItemActionPerformed
            DriverView x = new  DriverView();
            Desktop.add(x);
            x.setVisible(true);
                   
    }//GEN-LAST:event_DriversMenuItemActionPerformed

    private void UseAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseAsMenuItemActionPerformed
            Car c=new Car();
        ArrayList<Car> cars= c.ListAllCars();
        String [] Names = new String[cars.size()];
        int [] Use = new int[cars.size()];
        for(int i=0;i<cars.size();i++)
        {
            if (cars.get(i).getUseAs().equals("Taxi")) {
                Use[i]=2;
            }
            else
            {
                Use [i]=1;
            }
            Names[i]=cars.get(i).getBrands().getBName()+""+cars.get(i).getCarNo();
        }
        String Explain="Car Use\n 1 is Individual use\n2 is Taxi";
        String Explain_2="Use Of Car";
        Barchart chart = new Barchart(" Car Use Report ", Names, Use,Explain,Explain_2);

        chart.pack();
        RefineryUtilities.centerFrameOnScreen(chart);
        chart.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_UseAsMenuItemActionPerformed

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CarMenuItem;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem DriversMenuItem;
    private javax.swing.JMenuItem EmailMenuItem;
    private javax.swing.JMenuItem EmployeeMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem StatusReportMenuItem;
    private javax.swing.JMenuItem UseAsMenuItem;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
